#!/bin/bash

# This file needs to be sourced.

# Define update error codes
UPDATE_OK=(0 "SUCCESS")
GENERAL_FAILURE_ERROR=(1 "GENERAL FAILURE ERROR")
INCOMPAT_BOARD_TYPE_ERROR=(2 "INCOMPATIBLE BOARD TYPE")
DOWNGRADING_ERROR=(3 "DOWNNGRADING IS NOT SUPPORTED")
VAR_MOUNT_ERROR=(4 "EFI VARIABLES MOUNTING ERROR")
PART_MOUNT_ERROR=(5 "ERROR MOUNTING PARTITION")
# Download and write errors
BNXTNVM_DL_ERROR=(6 "FAILED TO DOWNLOAD BNXTNVM")
FIP_DL_ERROR=(7 "FAILED TO DOWNLOAD FIP IMAGE")
FIP_WRITE_ERROR=(8 "FAILED TO WRITE fip.bin")
NITRO_DL_ERROR=(9 "FAILED TO DOWNLOAD NITRO IMAGE")
NITRO_UPD_ERROR=(10 "FAILED TO UPDATE NITRO")
ROOTFS_CHUNK_LIST_DL_ERROR=(12 "FAILED TO DOWNLOAD ROOTFS CHUNKS LIST")
NEXT_ROOTFS_CHUNK_DL_ERROR=(13 "FAILED TO DOWNLOAD NEXT ROOTFS CHUNK")
ROOTFS_CHUNK_RECOVERY_ERROR=(14 "FAILED TO WRITE ROOTFS CHUNK for Recovery PARTITION")
ROOTFS_CHUNK_SLOT_WRITE_ERROR=(15 "FAILED TO WRITE ROOTFS CHUNK FOR SLOT $rootfs_slot")
DTB_RECOVERY_DL_ERROR=(16 "FAILED TO DOWNLOAD DTB FILE FOR RECOVERY IMAGE")
DTB_SLOT_DL_ERROR=(17 "FAILED TO DOWNLOAD DTB IMAGE FOR SLOT $dtb_slot")
KERNEL_RECOVERY_DL_ERROR=(18 "FAILED TO DOWNLOAD KERNEL RECOVERY IMAGE")
KERNEL_SLOT_DL_ERROR=(19 "FAILED TO DOWNLOAD KERNEL IMAGE FOR SLOT $kernel_slot")

# Integrity errors
FIP_INTEGRITY_ERROR=(20 "INTEGRITY CHECK FAILED (FIP)")
NITRO_INTEGRITY_ERROR=(21 "INTEGRITY CHECK FAILED (NITRO)")
CHUNK_LIST_INTEGRITY_ERROR=(22 "INTEGRITY CHECK FAILED (CHUNKS LIST)")
CHUNK_INTEGRITY_ERROR=(23 "INTEGRITY CHECK FAILED (CHUNK)")
DTB_RECOVERY_INTEGRITY_ERROR=(24 "INTEGRITY CHECK FAILED (DTB RECOVERY)")
DTB_SLOT_INTEGRITY_ERROR=(25 "INTEGRITY CHECK FAILED (DTB)")
KERNEL_RECOVERY_INTEGRITY_ERROR=(26 "INTEGRITY CHECK FAILED (KERNEL RECOVERY)")
KERNEL_SLOT_INTEGRITY_ERROR=(27 "INTEGRITY CHECK FAILED (KERNEL)")
MD5SUM_PARAMETER_ERROR=(28 "MD5SUM.TXT PARAMETER ERROR, FILE DOES NOT EXIST, OR MISMATCH")
MD5SUMTXT_MISSING_ERROR=(29 "MD5SUMTXT FILE COULD NOT BE DOWNLOADED")

# Wrong parameters errors
INPUT_PARAM_NOT_SPECIFIED_ERROR=(50 "INPUT PARAMETER NOT SPECIFIED")
WRONG_PARAMETER_ERROR=(51 "WRONG PARAMETER(S)")
WRONG_KERNEL_SLOT_ERROR=(52 "INVALID KERNEL SLOT REQUESTED")
WRONG_DTB_SLOT_ERROR=(53 "INVALID DTB SLOT REQUESTED")
WRONG_ROOTFS_SLOT_ERROR=(54 "INVALID ROOTFS SLOT REQUESTED")

warn_start=60
# Warnings requiring attention
UPDATE_AT_ONCE_ROOTFS_WRN=(60 "UPDATE_AT_ONCE REQUIRES BOOTING INTO RECOVERY")
ACTIVE_ROOTFS_WRN=(61 "CANNOT FLASH ACTIVE ROOTFS")
ACTIVE_RECOVERY_WRN=(62 "CANNOT FLASH RECOVERY FROM RECOVERY")

# Resulting filename to report errors/warnings
upd_result_filename="/usr/share/edk2/last_updateme_result.txt"